#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apt'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/nodejs'
mod 'ripienaar/module_data'

mod 'immerzeel/dotfiles',
  :git => 'git://github.com/immerzeel/puppet-dotfiles.git'

mod 'immerzeel/ohmyzsh',
  :git => 'git://github.com/immerzeel/puppet-ohmyzsh.git'

mod 'immerzeel/vim',
  :git => 'git://github.com/immerzeel/puppet-vim.git'

mod 'immerzeel/jekyll',
  :git => 'git://github.com/immerzeel/puppet-jekyll.git'

# Install Puppet provider for managing OS X Plists.
# mod 'property_list_key',
#   :git => 'https://github.com/glarizza/puppet-property_list_key.git'
