#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'puppetlabs/apt'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/nodejs'

mod 'dotfiles',
  :git => 'git://github.com/immerzeel/puppet-dotfiles.git'

mod 'ohmyzsh',
  :git => 'git://github.com/immerzeel/puppet-ohmyzsh.git'

mod 'vim',
  :git => 'git://github.com/immerzeel/puppet-vim.git'

mod 'jekyll',
  :git => 'git://github.com/immerzeel/puppet-jekyll.git'

# Install Puppet provider for managing OS X Plists.
# mod 'property_list_key',
#   :git => 'https://github.com/glarizza/puppet-property_list_key.git'
